# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'KarwaRide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KarwaRide
    pod 'Alamofire', '~> 4.4'
    pod 'MagicalRecord'
    pod 'GoogleMaps'
    pod 'FacebookCore'
    pod 'ScalingCarousel'
    pod 'SwiftDate'
    pod 'SwiftyJSON'
end
