# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'KarwaRide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KarwaRide
    pod 'Alamofire', '~> 4.4'
    pod 'MagicalRecord'
    pod 'GoogleMaps', '~> 2.7'
    pod 'FacebookCore'
    pod 'ScalingCarousel'
    pod 'SwiftDate'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    pod 'JTMaterialSwitch'
    pod 'Cosmos'
    pod 'Kingfisher', '~> 4.0'
    pod 'RKTagsView'
    pod 'Fabric'
    pod 'Crashlytics', '~> 3.10.5'
    pod 'Firebase/Core'
    pod 'SAConfettiView'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'Toast-Swift'
    pod 'XLActionController'
    pod 'XLActionController/Youtube'
    pod 'DDViewSwitcher'

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        plist_buddy = "/usr/libexec/PlistBuddy"
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        
        puts "Add arm64 to #{target} to make it pass iTC verification."
        
        `#{plist_buddy} -c "Add UIRequiredDeviceCapabilities array" "#{plist}"`
        `#{plist_buddy} -c "Add UIRequiredDeviceCapabilities:0 string arm64" "#{plist}"`
    end
end
