# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'KarwaRide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KarwaRide
  pod 'Alamofire', '~> 4.4'
  pod 'GoogleMaps', '~> 2.7'
  pod 'FacebookCore', '~> 0.4.0'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'XLActionController', '~> 4.1.1'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'Kingfisher', '~> 4.0'
  pod 'Crashlytics', '~> 3.10.5'
  pod 'NotificationBannerSwift', '1.6.3'
  pod 'MarqueeLabel/Swift', '3.1.6'
  pod 'Firebase/Core'

    pod 'MagicalRecord'
    pod 'ScalingCarousel'
    pod 'SwiftDate'
    pod 'SVProgressHUD'
    pod 'JTMaterialSwitch'
    pod 'Cosmos'
    pod 'RKTagsView'
    pod 'Fabric'
    pod 'SAConfettiView'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'XLActionController/Youtube'
    pod 'DDViewSwitcher'
    pod 'BarcodeScanner'
    pod 'CardIO'
    pod 'CDAlertView'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        plist_buddy = "/usr/libexec/PlistBuddy"
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        
        puts "Add arm64 to #{target} to make it pass iTC verification."
        
        `#{plist_buddy} -c "Add UIRequiredDeviceCapabilities array" "#{plist}"`
        `#{plist_buddy} -c "Add UIRequiredDeviceCapabilities:0 string arm64" "#{plist}"`
    end
end
